type: chart
builds:
  - image: samsung_cnct/cluster-manager-api
    context: cluster-manager-api
    chart: cluster-manager-api
    value: image.repo
    dockerContext: .
  - image: samsung_cnct/kind
    context: kind
    dockerContext: .
deployments:
  - chart: cluster-manager-api
    timeout: 600
    retries: 2
    release: cluster-manager-api
prod:
  doDeploy: none
